
#delete row
#DELETE http://localhost:9090/hs/delete/1

#Update
#PUT http://localhost:9090/hs/update/1

#{
#  "code": 123456,
#  "name": "Updated Name"
#}

#Get table
#GET http://localhost:9090/hs/getall


#Add data
#POST http://localhost:9090/hs/add
#Content-Type: application/json
#
#{
#  "code": 123456,
#  "name": "Electronics HS Code"
#}